# Generated by Django 2.0.7 on 2018-07-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgetastic_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='m_name',
        ),
    ]
